### ISSUE TITLE
How to retrieve unprocessed messages after service recovery?

### ISSUE THREAD

**Issue by Idanby** [learningcom/Learning.EventStore#1]
Hi,
First of all I would like to say that Learning.EventStore is really awesome package. Well done.
I have a small question about polling unprocessed messages from published Q.
While my service is down, the publish Q in Redis still collecte event messages as expected.
Once my service subscribe again (after recovery) via RedisEventSubscriber, the published Q still contains all messages but my handler does not getting them (until new event/message pushed).
What can I do about it?
How can I get them after recovery?

Thanks.

**Comment by steelheaddigital** [comment]
Hi there, thanks for the kind words about the library, I'm glad it's useful to you. And, sorry for the long delay in replying to you, for some reason Github didn't notify me of your comment, I'll have to check my notification settings. You bring up an excellent point. In earlier versions of the library, there was code to check the queue on startup and to process any messages that were waiting in there. The problem with it was that it ran before the subscription actually subscribed to the event stream.  We ran into a problem where during a release, one of our queues got really long. Therefore, when the service started up, it was taking a long time to process all of the events before the subscriber actually subscribed and we were missing events. We run multiple instances of each of our services, so the queue is eventually cleared out anyway as each service picks up new events. Therefore, we removed that startup code since it wasn't necessary for us and was causing us some problems. This is probably something that should be in there though and I'll look into putting that code back in. Thanks a lot!

**Comment by steelheaddigital** [comment]
@Idanby This is fixed in the latest versions. I added code to the RedisEventSubscriber to loop through any items in the Published queue and process them when the SubscribeAsync() method is called. As long as you are calling that in your startup code, the queue will be cleared when a service comes back up after being down for a while. See [this commit](https://github.com/learningcom/Learning.EventStore/commit/a00b1a0fcb079b30d48bac00aedaf9846bb212d9). Fresh Nuget packages have also been published. Thanks for using the library and for submitting this issue, take care!
